attempt at upgrading dependencies
Upgraded all pom dependencies to latest versions -
only three unresolved compiler issues:

src/main/scala/com/stripe/simmer/Aggregators.scala:39: error: type mismatch;
 found   : scala.util.Try[A]
 required: Option[A]
			injection.invert(serialized.drop(MAGIC.size))
                                        ^
src/main/scala/com/stripe/simmer/Aggregators.scala:55: error: not found: value KryoInjection
  	KryoInjection.asInstanceOf[Injection[A, Array[Byte]]] andThen
        ^
src/main/scala/com/stripe/simmer/Aggregators.scala:203: error: type mismatch;
 found   : com.twitter.algebird.MinHashSignature
 required: Array[Byte]
	def prepare(in : String) = monoid.init(in)

Seems relatively mild.